heat_template_version: 2015-10-15

description: >
  HOT Tenplate to deploy two servers (iperf-server and iperf-client) into existing neutron tenant network and assign floating IP 
  addresse to the iperf-server so he is routable from the public network

parameters:
  image:
    type: string
    description: image for iperf server and client
    default: 4beaa052-8e21-4264-9ed9-2dfa41fd254f 
  flavor:
    type: string
    description: flavor for iperf server and client
    default: kvm.m1.small
  public_net_id:
    type: string
    description: ID of public network for which floating IP addresses will be allocated
  private_net_id:
    type: string
    description: ID of private network into which servers get deployed
  private_subnet_id:
    type: string
    description: ID of private sub network into which servers get deployed
  timeout:
    type: number
    description: Timeout for WaitCondition
    default: 600

resources:
  iperf-client:
    type: "OS::Heat::ResourceGroup"
    depends_on:
      - iperf-server
    properties:
      count: 1
      resource_def:
        type: iperf-client.yaml
        properties:
          name: iperf-client
          image: { get_param: image }
          flavor: { get_param: flavor }
          public_net_id: { get_param: public_net_id }
          private_subnet_id: { get_param: private_subnet_id }
          private_net_id: { get_param: private_net_id }
          timeout: { get_param: timeout }

  iperf-server:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: 1
      resource_def:
        type: iperf-server.yaml
        properties:
          name: iperf-server
          image: { get_param: image }
          flavor: { get_param: flavor }
          private_subnet_id: { get_param: private_subnet_id }
          private_net_id: { get_param: private_net_id }
          timeout: { get_param: timeout }

outputs:
  iperf-client_public_ip:
    description: Floating IP of iperf-client in public network
    value: { get_attr: [ iperf-client, iperf-client_public_ip ] }

  iperf-server_private_ip:
    description: IP of the iperf-server in the private network
    value: { get_attr: [ iperf-server, iperf-server_private_ip ] }
